name: Build and Release WPF App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Ensures submodules are fetched
          fetch-depth: 0  # Required for submodules to have full history

      - name: Initialize and Update Submodules
        run: git submodule update --init --recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'  # Adjust to your target .NET version

      - name: Restore Dependencies
        run: dotnet restore TaskManagerGUI.sln

      - name: Build Solution
        run: dotnet build TaskManagerGUI.sln --configuration Release --no-restore

      - name: Publish Application
        run: dotnet publish TaskManagerGUI.sln --configuration Release --output publish

      - name: Package Release
        run: Compress-Archive -Path publish\* -DestinationPath TaskManagerGUI.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: "TaskManagerGUI Release v1.0.${{ github.run_number }}"
          body: "Automated release for TaskManagerGUI"
          draft: false
          prerelease: false
          files: TaskManagerGUI.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
